/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: "#16a34a",
                secondary: "#dcfce7",
                background: "#fff",
                foreground: "oklch(0.145 0 0)",
                card: "#fff",
                card_foreground: "oklch(0.145 0 0)",
                font_size: "16px",
                popover: "oklch(1 0 0)",
                popover_foreground: "oklch(0.145 0 0)",
                primary_foreground: "#ffffff",
                secondaryForeground: "#166534",
                muted: "#f3f4f6",
                muted_foreground: "#6b7280",
                accent: "#bbf7d0",
                accent_foreground: "#166534",
                destructive: "#d4183d",
                destructive_foreground: "#ffffff",
                border: "rgba(0, 0, 0, 0.1)",
                input: "transparent",
                input_background: "#f9fafb",
                switch_background: "#cbced4",
                font_weight_medium: "500",
                font_weight_normal: "400",
                ring: "#16a34a",
                chart_1: "oklch(0.646 0.222 41.116)",
                chart_2: "oklch(0.6 0.118 184.704)",
                chart_3: "oklch(0.398 0.07 227.392)",
                chart_4: "oklch(0.828 0.189 84.429)",
                chart_5: "oklch(0.769 0.188 70.08)",
                radius: "0.625rem",
                sidebar: "oklch(0.985 0 0)",
                sidebar_foreground: "oklch(0.145 0 0)",
                sidebar_primary: "#16a34a",
                sidebar_primary_foreground: "#ffffff",
                sidebar_accent: "oklch(0.97 0 0)",
                sidebar_accent_foreground: "oklch(0.205 0 0)",
                sidebar_border: "oklch(0.922 0 0)",
                sidebar_ring: "oklch(0.708 0 0)",

            },
        },
    },
    plugins: [],
};
